services:
  - type: web
    name: mcp-analytics-server
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false

